steps:
  # name: gcr.io/$PROJECT_ID/protoc:latest
  # args:
  #   - -I:readss
  #   - readss/readss.proto
  #   - --js_out=import_style=commonjs:readss
  #   - --grpc-web_out=import_style=commonjs,mode=grpcwebtext:readss
  #   - --go_out=plugins=grpc:readss
  - name: gcr.io/cloud-builders/docker:latest
    args:
      - build
      - --cache-from
      - gcr.io/$PROJECT_ID/$_IMG:latest
      - -t
      - gcr.io/$PROJECT_ID/$_IMG:latest
      - -t
      - gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/kubectl:latest
    args:
      - set
      - image
      - deploy
      - readss
      - "*=gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster12"
images:
  - gcr.io/$PROJECT_ID/$_IMG:latest
  - gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
substitutions:
  _IMG: readss-server
