steps:
  # name: gcr.io/$PROJECT_ID/protoc:latest
  # args:
  #   - -I:readss
  #   - readss/readss.proto
  #   - --js_out=import_style=commonjs:readss
  #   - --grpc-web_out=import_style=commonjs,mode=grpcwebtext:readss
  #   - --go_out=plugins=grpc:readss
  - name: gcr.io/cloud-builders/docker:latest
    args:
      - build
      - --cache-from
      - $_IMG
      - -t
      - $_IMG
      - .
images:
  - $_IMG
substitutions:
  _IMG: gcr.io/$PROJECT_ID/readss-server:latest
