// Code generated by protoc-gen-go. DO NOT EDIT.
// source: readss.proto

package readss

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e5489cbafef27c, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListReply struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e5489cbafef27c, []int{1}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type Article struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Reltime              string   `protobuf:"bytes,5,opt,name=reltime,proto3" json:"reltime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e5489cbafef27c, []int{2}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Article) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Article) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Article) GetReltime() string {
	if m != nil {
		return m.Reltime
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "readss.ListRequest")
	proto.RegisterType((*ListReply)(nil), "readss.ListReply")
	proto.RegisterType((*Article)(nil), "readss.Article")
}

func init() { proto.RegisterFile("readss.proto", fileDescriptor_14e5489cbafef27c) }

var fileDescriptor_14e5489cbafef27c = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0xab, 0x82, 0x40,
	0x10, 0xc7, 0xf1, 0xa9, 0xeb, 0x73, 0x7c, 0x8f, 0x6a, 0x8a, 0x58, 0x3a, 0x89, 0x27, 0x21, 0xf0,
	0x60, 0x17, 0xaf, 0xdd, 0x3b, 0xf9, 0x0d, 0xcc, 0xe6, 0xb0, 0xb0, 0xa1, 0xed, 0xae, 0x84, 0xdf,
	0x3e, 0xdc, 0xd5, 0xa8, 0xdb, 0xff, 0xf7, 0x63, 0x18, 0xfe, 0x33, 0xf0, 0xa7, 0xa8, 0xb9, 0x69,
	0x5d, 0xf4, 0xaa, 0x33, 0x1d, 0x32, 0x47, 0xd9, 0x3f, 0x24, 0x17, 0xa1, 0x4d, 0x4d, 0x8f, 0x81,
	0xb4, 0xc9, 0x2a, 0x88, 0x1d, 0xf6, 0x72, 0xc4, 0x23, 0xfc, 0x36, 0xca, 0x88, 0x56, 0x92, 0xe6,
	0x5e, 0xea, 0xe7, 0x49, 0xb9, 0x2a, 0xe6, 0x25, 0x67, 0xe7, 0xeb, 0xf7, 0x40, 0xf6, 0x84, 0x68,
	0x96, 0xb8, 0x83, 0xd0, 0x08, 0x23, 0x89, 0x7b, 0xa9, 0x97, 0xc7, 0xb5, 0x03, 0x5c, 0x83, 0x3f,
	0x28, 0xc9, 0x7f, 0xac, 0x9b, 0x22, 0xee, 0x81, 0xe9, 0x6e, 0x50, 0x2d, 0x71, 0xdf, 0xca, 0x99,
	0x10, 0x21, 0x30, 0xe2, 0x4e, 0x3c, 0xb0, 0xd6, 0x66, 0xe4, 0x10, 0x29, 0x92, 0x56, 0x87, 0x56,
	0x2f, 0x58, 0x56, 0xc0, 0xa6, 0xca, 0xa4, 0xb0, 0x80, 0x60, 0x4a, 0xb8, 0x5d, 0x5a, 0x7e, 0x5c,
	0x76, 0xd8, 0x7c, 0xcb, 0x5e, 0x8e, 0x57, 0x66, 0x5f, 0x71, 0x7a, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x77, 0x3d, 0x06, 0x34, 0x1a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ListerClient is the client API for Lister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListerClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
}

type listerClient struct {
	cc *grpc.ClientConn
}

func NewListerClient(cc *grpc.ClientConn) ListerClient {
	return &listerClient{cc}
}

func (c *listerClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/readss.Lister/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListerServer is the server API for Lister service.
type ListerServer interface {
	List(context.Context, *ListRequest) (*ListReply, error)
}

// UnimplementedListerServer can be embedded to have forward compatible implementations.
type UnimplementedListerServer struct {
}

func (*UnimplementedListerServer) List(ctx context.Context, req *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterListerServer(s *grpc.Server, srv ListerServer) {
	s.RegisterService(&_Lister_serviceDesc, srv)
}

func _Lister_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/readss.Lister/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListerServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "readss.Lister",
	HandlerType: (*ListerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Lister_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "readss.proto",
}
